### ISSUE TITLE
Wrong auto closure of the set of properties once the last css prop doesn't have its semicolon  

### ISSUE THREAD

**Issue by ilsantuzzo** [Ju99ernaut/grapesjs-component-code-editor#1]
This plugin is amazing, but I have found a small issue FYI.

![ezgif-6-c8016c2b9f51](https://user-images.githubusercontent.com/5839445/93463637-50356880-f8e8-11ea-9961-95be2e5ddb49.gif)

**Comment by Ju99ernaut** [comment]
Will be fixed in the next release, Thanks

**Comment by ilsantuzzo** [comment]
> Will be fixed in the next release, Thanks

I see your changes and it works! thx a lot!!
