### ISSUE TITLE
Failed to load in safari

### ISSUE THREAD

**Issue by jgui1129** [Ju99ernaut/grapesjs-component-code-editor#20]
https://github.com/Ju99ernaut/grapesjs-component-code-editor/blob/61025da5256ad2d52edbf745edf177acf14645d3/src/code-editor/index.js#L140

I tried using 

```
.split(/(?:}\n)/g)
```

Does this ok for a PR?

**Comment by Ju99ernaut** [comment]
A PR would be welcome.

**Comment by maxym-codecare** [comment]
Hi @Ju99ernaut, sorry for commenting on a closed issue, but seems that it still not working

**Comment by Ju99ernaut** [comment]
I'm not sure if this was fixed, I don't have safari so I was waiting for a PR
