### ISSUE TITLE
Confict with gjs-preset-webpage

### ISSUE THREAD

**Issue by thanhdevapp** [Ju99ernaut/grapesjs-component-code-editor#21]
Please check code, code auto close

demo online: https://codepen.io/thanhdevapp/pen/OJmVwBO

**Comment by Ju99ernaut** [comment]
By default `gjs-preset-webpage` opens the style manager every time a component is selected https://github.com/artf/grapesjs-preset-webpage/blob/3e5a9e12998c9a32b6f1199953084163678e6c17/src/panels/index.js#L108
Add this option to your `pluginOpts`:

```js
pluginsOpts: {
    "gjs-preset-webpage": {
      showStylesOnChange: 0
    }
}
```
