### ISSUE TITLE
CSS duplication on click Apply in CSS editor

### ISSUE THREAD

**Issue by tom-codelooms** [Ju99ernaut/grapesjs-component-code-editor#27]
Hi Thank you for your plugin which is very helpful to me. 
I have some issues while reloading the style from db and try to update CSS. 

The steps are given below

I saved the data in server and using load page url to load the content again 

After loading the css editor in the component shows the correct CSS, and when I just click Apply and check the Source code, it shows twice the same css again

<img width="1683" alt="Screenshot 2021-12-09 at 8 44 19 PM" src="https://user-images.githubusercontent.com/94916117/145422861-7b0d1d4e-271d-4b1d-8e77-23f702c05fab.png">
<img width="1259" alt="Screenshot 2021-12-09 at 8 44 37 PM" src="https://user-images.githubusercontent.com/94916117/145422890-45334b5b-65fb-4552-a908-0c89b1edd2b1.png">

Could you please give the suggestion to fix this issue?

Regards,
Tom

**Comment by Ju99ernaut** [comment]
No idea to be honest, you could try selecting the duplicate css and hitting delete

**Comment by omergr8** [comment]
I am experiencing the same issue, every time I click on apply, it keeps on adding duplicate css.

**Comment by iamqinglong** [comment]
I am experiencing this too.
