### ISSUE TITLE
table cell content going to parent on aplly

### ISSUE THREAD

**Issue by Gabriel5934** [Ju99ernaut/grapesjs-component-code-editor#29]
I have the following code on my editor

```
<tr id="i2fxz" data-gjs-type="row" draggable="true" data-highlightable="1">
  <td id="im87t" data-gjs-type="cell" draggable="true" data-highlightable="1"class="gjs-selected"> Hello World </td>
</tr>
```

When I click Aplly with the TD selected, the TD gets deleted and the code goes to the TR

**Comment by Ju99ernaut** [comment]
Looks like you've selected TR, which is why you get `<tr...` in the editor. If you have TD selected you should only get `<td...`
