### ISSUE TITLE
clearData is not working properly

### ISSUE THREAD

**Issue by ilsantuzzo** [Ju99ernaut/grapesjs-component-code-editor#3]
I see that the clearData option is not removing the GJS attributes also if is set on true. I can't see any differences when I leave the option on false. I have created this [jsfiddle](https://jsfiddle.net/gym6kpbs/8/) where to check it out. Should it remove all the data-gjs.. and the draggable="true" data-highlightable="1" ?

**Comment by Ju99ernaut** [comment]
Thanks again, will definitely fix this one soon.

**Comment by ilsantuzzo** [comment]
> Thanks again, will definitely fix this one soon.
Thx a lot you have been very fast
