### ISSUE TITLE
Is it possible to block the editor?

### ISSUE THREAD

**Issue by vizardkill** [Ju99ernaut/grapesjs-component-code-editor#38]
First of all bro, I love your projects regarding Grapes I have learned a lot from your code to better understand custom plugin creation.

In this plugin a doubt arose, as you know I am building a site where 4 default pages are shown with certain static blocks, such as a list of products, a shopping cart, etc.

I wanted to know if it is possible that if I select a specific component I cannot show the user the code editor? This way I avoid modifying a block that in theory is not editable

**Comment by Ju99ernaut** [comment]
This isn't possible, even components that can't be edited from the canvas can still be edited from the code-editor. I think you can still achieve this manually, just check if the selected component is editable, if it's not hide the code-editor(if visible) and the panel button.

**Comment by vizardkill** [comment]
Yes, it would be like calling the command where the block is selected to prevent the code editor from rendering, but I don't know if you have an example of the command?

**Comment by Ju99ernaut** [comment]
You could make use of the `component:selected` hook:
```js
editor.on('component:selected', (component) => {
   // hide or show code  editor 
});
```
