### ISSUE TITLE
Can't delete a property

### ISSUE THREAD

**Issue by ilsantuzzo** [Ju99ernaut/grapesjs-component-code-editor#5]
If you try to delete the padding property using the code editor [here](https://jsfiddle.net/gym6kpbs/8/) on the "Hello word!!" and then try to apply your changes it won't work. But I see that is working properly when I just change the property.

**Comment by Ju99ernaut** [comment]
Thanks, I'll take a look at it.

**Comment by ilsantuzzo** [comment]
Great!!! thx!
