### ISSUE TITLE
integrate this plugin into my grapejs already in place

### ISSUE THREAD

**Issue by VConsulting** [Ju99ernaut/grapesjs-component-code-editor#6]
Hello,
I am looking to integrate this plugin into my grapejs already in place.

Only I can't get him to add his panel without destroying the others
If I do :
```
//...
  panels: {
    defaults: [
      {
        buttons: [
          //...
          {
            attributes: { title: 'Open Code' },
            className: 'fa fa-code',
            command: 'open-code',
            id: 'open-code'
          }
          //...
        ],
        id: 'views'
      }
    ]
  },
  //...
```
That code is present, but the other tab disappears that resets the config.
How to tell him to add it?

**Comment by Ju99ernaut** [comment]
You can add it to the panels using the same method in `index.html`.

https://github.com/Ju99ernaut/grapesjs-component-code-editor/blob/5a85578279355836081a1aaabcf50a9ddaa4e900/index.html#L107-L119
