### ISSUE TITLE
Not Recognized as plugin

### ISSUE THREAD

**Issue by devtechk** [Ju99ernaut/grapesjs-component-code-editor#9]
Hi, I'm using angular I've implemented yet the gjs-preset-webpage and I'd like to add the grapesjs-component-code-editor and the postcss but they're not recognized.

imported like this:
import 'grapesjs-parser-postcss';
import 'grapesjs-component-code-editor';

Used:
      plugins: ['gjs-preset-webpage',  'grapesjs-parser-postcss', 'grapesjs-component-code-editor', driveForcePlugin],

Screenshot attached.

Hope you can help me. 
Thanks 

![image](https://user-images.githubusercontent.com/22073497/109846737-c5a2b480-7c4e-11eb-84d6-6a9879de72ef.png)

**Comment by Ju99ernaut** [comment]
Importing should be something like this:

```js
// ...
import grapesjs from 'grapesjs';
import codeEditor from 'grapesjs-component-code-editor';
import parserPostCSS from 'grapesjs-parser-postcss';
import 'grapesjs-component-code-editor/dist/grapesjs-component-code-editor.min.css';

const editor = grapesjs.init({
  container : '#gjs',
  // ...
  plugins: [
    editor => codeEditor(editor, { /* options */ }),
    parserPostCSS,
  ],
  // ...
});
// ...
```

**Comment by devtechk** [comment]
Thank you,This morning I've tried in a similar way and it worked. I'll try your way too!
